project:
  default-view: redirect:/swagger-ui.html

spring:
  application:
    name: test
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:oracle:thin:@10.1.10.131:30089:XE
    username: USERROLE
    password: USERROLE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 7739

apache:
  rocketmq:
    consumer:
      consumerGroup: Consumer # 消费者的组名
    producer:
      producerGroup: Producer # 生产者的组名
    namesrvAddr: 10.10.101.67:9876 # NameServer地址
