project:
  default-view: redirect:/swagger-ui.html

spring:
  application:
    name: test
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:oracle:thin:@10.1.10.131:30089:XE
    username: USERROLE
    password: USERROLE
  #mongo
  data:
    mongodb:
      uri: mongodb://10.1.11.112:33001/test

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 7739