project:
  default-view: redirect:/swagger-ui.html

spring:
  application:
    name: framework
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:oracle:thin:@10.1.11.111:1521:XE
    username: ROOT
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: oracle.jdbc.OracleDriver
      pool:
        initialSize: 5
        maxActive: 10
        minIdle: 5
        maxWait: 10000
        validationQuery: SELECT 1 FROM DUAL
        testOnBorrow: true
    #schema: classpath:sql/data.sql
  #mongo
  data:
    mongodb:
      uri: mongodb://10.1.11.112:33001/test

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  typeAliasesPackage: com.harmonycloud.*.adapter.outbound.database.entity
  global-config:
    #    id-type: 0 # 数据库自增id
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    sql-inector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

apache:
  rocketmq:
    consumer:
      consumerGroup: Consumer # 消费者的组名
    producer:
      producerGroup: Producer # 生产者的组名
    namesrvAddr: 10.10.101.67:9876 # NameServer地址

sftp:
  client:
    protocol: sftp
    # ip地址
    host: 10.1.11.118
    # 端口
    port: 22
    # 用户名
    username: root
    # 密码
    password: 123456
    # 根路径
    root: /
    # 密钥文件路径
    privateKey:
    # 密钥的密码
    passphrase:
    #
    sessionStrictHostKeyChecking: no
    # session连接超时时间
    sessionConnectTimeout: 15000
    # channel连接超时时间
    channelConnectedTimeout: 15000

server:
  port: 7739
