spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: oracle.jdbc.OracleDriver
      pool:
        initialSize: 5
        maxActive: 10
        minIdle: 5
        maxWait: 10000
        validationQuery: SELECT 1 FROM DUAL
        testOnBorrow: true

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  typeAliasesPackage: com.harmonycloud.*.adapter.outbound.database.dataobject
  global-config:
    #    id-type: 0 # 数据库自增id
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    sql-inector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false